# Generated by Django 3.0.1 on 2020-01-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('albumId', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(unique=True, verbose_name='Titulo')),
                ('imagen', models.TextField(verbose_name='Imagen')),
                ('precioOriginal', models.TextField(verbose_name='Precio original')),
                ('precioDescuento', models.TextField(verbose_name='Precio con descuento')),
                ('fecha', models.DateField(verbose_name='Fecha de lanzamiento')),
                ('ventas', models.IntegerField(verbose_name='Numero de ventas')),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
    ]
