# Generated by Django 3.0.1 on 2020-01-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.TextField(verbose_name='Titulo'),
        ),
    ]
